r"""
Table II, written by code from results/tabla2.json instead of typed into the paper.

Why this exists: every cost cell of Table II had drifted from its source, and the
reason was that the table lived in the .tex as text. A number that is typed once is
a number that can stop matching the run that produced it. This script closes that
path: the table is generated, and a check compares what it generates against what
the paper carries.

It writes the tabular to paper/tabla2.tex and then splices that same tabular into
the manuscript between two markers, so the .tex stays a single self-contained file
to upload to Overleaf. The caption is not touched: the prose belongs to the authors,
the numbers belong to the run.

  python resultados.py           write paper/tabla2.tex and splice it into the .tex
  python resultados.py --check   compare only, change nothing, non-zero if they differ

Reads:  results/tabla2.json
Writes: paper/tabla2.tex, and the marked region of the manuscript
"""
import io
import os
import sys
import json
import re

BASE = r"C:\Users\melvi\Documents\Maestria\19. Seminario de Tesis II\Anteproyecto - Seminario II"
TEX = os.path.join(BASE, "Anteproyecto_G3_Seminario_Tesis_I.tex")
OUT = os.path.join(BASE, "paper", "tabla2.tex")
BEGIN, END = "% BEGIN tabla2 (generated by resultados.py; do not edit by hand)", "% END tabla2"
CHECK = "--check" in sys.argv

d = json.load(open(os.path.join(BASE, "results", "tabla2.json"), encoding="utf-8"))
models = d["models"]


def num(mean, std):
    return "$%.3f \\pm %.3f$" % (mean, std)


def cost(c, kind):
    """size / training seconds / inference milliseconds, as the caption defines it.

    An agent row prints 0 because it trains nothing; every other row that rounds to
    zero prints $<$0.01, because it did train and the time is simply small."""
    size = "{:,}".format(c["parameters"])
    t = c["training_seconds"]
    tr = "0" if kind == "agent" else ("$<$0.01" if t < 0.01 else "%.0f" % t)
    inf = "$<$0.001" if c["inference_ms_per_episode"] < 0.001 else "%.3f" % c["inference_ms_per_episode"]
    return "%s / %s / %s" % (size, tr, inf)


# the best row on each metric is bold, and it is found here rather than remembered
best_p = max(models, key=lambda m: m["primary_mean"])["name"]
best_s = max(models, key=lambda m: m["secondary_mean"])["name"]

lines = [r"\begin{tabular}{@{}lccr@{}}", r"\toprule",
         r"Model & Macro $F_1$ & Recall@3 & \multicolumn{1}{c}{Cost} \\", r"\midrule"]
# the floor sits with the classics: the rules separate the three families the paper
# discusses, which are the classical models, the networks and the agent arms
BLOCK = {"floor": 0, "classic": 0, "network": 1, "agent": 2}
prev = None
for m in models:
    if prev is not None and BLOCK[m["kind"]] != prev:
        lines.append(r"\midrule")
    prev = BLOCK[m["kind"]]
    p = num(m["primary_mean"], m["primary_std_over_folds"])
    s = num(m["secondary_mean"], m["secondary_std_over_folds"])
    if m["name"] == best_p:
        p = r"$\mathbf{%.3f \pm %.3f}$" % (m["primary_mean"], m["primary_std_over_folds"])
    if m["name"] == best_s:
        s = r"$\mathbf{%.3f \pm %.3f}$" % (m["secondary_mean"], m["secondary_std_over_folds"])
    lines.append("%-15s & %s & %s & %s \\\\" % (m["name"], p, s, cost(m["cost"], m["kind"])))
lines += [r"\bottomrule", r"\end{tabular}"]
table = "\n".join(lines)

tex = io.open(TEX, encoding="utf-8").read()
current = re.search(r"\\begin\{tabular\}\{@\{\}lccr@\{\}\}.*?\\end\{tabular\}", tex, re.S)
assert current, "no se encontro la tabular de la Tabla II en el manuscrito"
same = current.group(0).strip() == table.strip()

if CHECK:
    print("la Tabla II del manuscrito %s lo que generan los datos"
          % ("COINCIDE con" if same else "NO coincide con"))
    if not same:
        for a, b in zip(current.group(0).splitlines(), table.splitlines()):
            if a.strip() != b.strip():
                print("  manuscrito: %s\n  generado  : %s" % (a.strip(), b.strip()))
    raise SystemExit(0 if same else 1)

os.makedirs(os.path.dirname(OUT), exist_ok=True)
io.open(OUT, "w", encoding="utf-8", newline="\n").write(table + "\n")
print("wrote paper/tabla2.tex")

if same:
    print("el manuscrito ya llevaba estos numeros: no se toco")
else:
    io.open(TEX, "w", encoding="utf-8", newline="\n").write(
        tex[:current.start()] + table + tex[current.end():])
    print("manuscrito actualizado con la tabla generada")

print()
print(table)
print()
print("mejor macro-F1 : %s" % best_p)
print("mejor Recall@3 : %s" % best_s)
print("dispersion     : %s" % d["_meta"]["dispersion_in_table"])
