r"""
Table II, written by code from results/tabla2.json instead of typed into the paper.

Why this exists: every cost cell of Table II had drifted from its source, and the
reason was that the table lived in the .tex as text. A number that is typed once is
a number that can stop matching the run that produced it. This script closes that
path: the table is generated, and a check compares what it generates against what
the paper carries.

It writes the tabular to paper/tabla2.tex and then splices that same tabular into
the manuscript between two markers, so the .tex stays a single self-contained file
to upload to Overleaf. The caption is not touched: the prose belongs to the authors,
the numbers belong to the run.

  python resultados.py           write the table and the paragraph, splice the table
  python resultados.py --check   compare only, change nothing, non-zero if they differ

The six sentences of paper/resultados.md are the ones requested: what is compared
and on what partition; the proposed method's number with its dispersion; the
difference against the best classic and whether it clears that dispersion; what the
agent adds, read off the ablation; the cost; and the main limitation. Each number is
substituted from the files, so the paragraph cannot drift from the table above it.

The figures are not produced here. They come from 09_plot_label_efficiency.py and
13_plot_architecture.py, under names that say what they are; the README maps each
artifact of the paper to its file and its script.

Reads:  results/tabla2.json, results/effect_sizes.csv, results/per_fold_f1.csv,
        results/human_load.csv
Writes: paper/tabla2.tex, paper/resultados.md, paper/resultados.tex, both of
        those regions of the manuscript, and the expected-results table of
        the README
"""
import io
import os
import sys
import json
import re
import textwrap

import numpy as np
import pandas as pd

BASE = os.path.dirname(os.path.abspath(__file__))
if not os.path.isfile(os.path.join(BASE, "requirements.txt")):
    BASE = os.path.dirname(BASE)      # the scripts live in code/, the project one level up
TEX = os.path.join(BASE, "Anteproyecto_G3_Seminario_Tesis_I.tex")
OUT = os.path.join(BASE, "paper", "tabla2.tex")
PBEGIN = "% BEGIN resultados (generated by resultados.py; do not edit by hand)"
PEND = "% END resultados"
CHECK = "--check" in sys.argv

d = json.load(open(os.path.join(BASE, "results", "tabla2.json"), encoding="utf-8"))
models = d["models"]


def num(mean, std):
    return "$%.3f \\pm %.3f$" % (mean, std)


def cost(c, kind):
    """size / training seconds / inference milliseconds, as the caption defines it.

    An agent row prints 0 because it trains nothing; every other row that rounds to
    zero prints $<$0.01, because it did train and the time is simply small."""
    size = "{:,}".format(c["parameters"])
    t = c["training_seconds"]
    tr = "0" if kind == "agent" else ("$<$0.01" if t < 0.01 else "%.0f" % t)
    inf = "$<$0.001" if c["inference_ms_per_episode"] < 0.001 else "%.3f" % c["inference_ms_per_episode"]
    return "%s / %s / %s" % (size, tr, inf)


# the best row on each metric is bold, and it is found here rather than remembered
best_p = max(models, key=lambda m: m["primary_mean"])["name"]
best_s = max(models, key=lambda m: m["secondary_mean"])["name"]

# la clave de las unidades vive en el encabezado, no en el pie: el pie tiene
# que caber en una linea y esto no cabia
lines = [r"\begin{tabular}{@{}lccr@{}}", r"\toprule",
         r"Model & Macro $F_1$ & Recall@3 & \multicolumn{1}{c}{Cost (size / s / ms)} \\", r"\midrule"]
# the floor sits with the classics: the rules separate the three families the paper
# discusses, which are the classical models, the networks and the agent arms
BLOCK = {"floor": 0, "classic": 0, "network": 1, "agent": 2}
prev = None
for m in models:
    if prev is not None and BLOCK[m["kind"]] != prev:
        lines.append(r"\midrule")
    prev = BLOCK[m["kind"]]
    p = num(m["primary_mean"], m["primary_std_over_folds"])
    s = num(m["secondary_mean"], m["secondary_std_over_folds"])
    if m["name"] == best_p:
        p = r"$\mathbf{%.3f \pm %.3f}$" % (m["primary_mean"], m["primary_std_over_folds"])
    if m["name"] == best_s:
        s = r"$\mathbf{%.3f \pm %.3f}$" % (m["secondary_mean"], m["secondary_std_over_folds"])
    lines.append("%-15s & %s & %s & %s \\\\" % (m["name"], p, s, cost(m["cost"], m["kind"])))
lines += [r"\bottomrule", r"\end{tabular}"]
table = "\n".join(lines)

# The manuscript is not in the repository: it lives in Overleaf and is
# gitignored. A clone therefore has the generated files but not the .tex, so the
# two spliced regions are skipped there instead of crashing, and --check reports
# on what it could actually compare.
HAS_TEX = os.path.isfile(TEX)
if not HAS_TEX:
    print("nota: %s no esta aqui (vive en Overleaf y esta gitignoreado);"
          % os.path.basename(TEX))
    print("      se generan y comparan los archivos versionados, no el manuscrito")

tex = io.open(TEX, encoding="utf-8").read() if HAS_TEX else ""
current = re.search(r"\\begin\{tabular\}\{@\{\}lccr@\{\}\}.*?\\end\{tabular\}", tex, re.S)
assert current or not HAS_TEX, "no se encontro la tabular de la Tabla II en el manuscrito"
same = current.group(0).strip() == table.strip() if current else True

# paper/tabla2.tex and paper/resultados.tex are committed, so they can be compared
# on a clone even when the manuscript is not here. This is what CI checks.
def compare(path, want, label):
    if not os.path.isfile(path):
        print("%s: no existe todavia" % label)
        return False
    got = io.open(path, encoding="utf-8").read().strip()
    ok = got == want.strip()
    print("%s %s lo que generan los datos" % (label, "COINCIDE con" if ok else "NO coincide con"))
    return ok

FILES_OK = []
if CHECK:
    FILES_OK.append(compare(OUT, table, "paper/tabla2.tex"))

if CHECK and not HAS_TEX:
    pass
elif CHECK:
    print("la Tabla II del manuscrito %s lo que generan los datos"
          % ("COINCIDE con" if same else "NO coincide con"))
    if not same:
        for a, b in zip(current.group(0).splitlines(), table.splitlines()):
            if a.strip() != b.strip():
                print("  manuscrito: %s\n  generado  : %s" % (a.strip(), b.strip()))
else:
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    io.open(OUT, "w", encoding="utf-8", newline="\n").write(table + "\n")
    print("wrote paper/tabla2.tex")
    if not HAS_TEX:
        pass
    elif same:
        print("el manuscrito ya llevaba estos numeros: no se toco")
    else:
        tex = tex[:current.start()] + table + tex[current.end():]
        io.open(TEX, "w", encoding="utf-8", newline="\n").write(tex)
        print("manuscrito actualizado con la tabla generada")
# ---------------------------------------------------------------- the paragraph
M = {m["name"]: m for m in models}
eff = pd.read_csv(os.path.join(BASE, "results", "effect_sizes.csv"))
pf = pd.read_csv(os.path.join(BASE, "results", "per_fold_f1.csv"))
hl = pd.read_csv(os.path.join(BASE, "results", "human_load.csv")).set_index("arm")
E = {(r.better, r.worse): r for r in eff.itertuples()}

pro, abl = M["Copilot v1"], M["No agent (abl.)"]
classics = [M[n] for n in ("Logistic reg.", "Random forest", "Gradient boost.")]
best_classic = max(classics, key=lambda m: m["primary_mean"])

# [3] the difference against the best classic, paired fold by fold and averaged by
# seed, which is how every other comparison in this paper is taken
KEY = {"Copilot v1": "proposed", "Logistic reg.": "logistic",
       "Random forest": "rf", "Gradient boost.": "hgb"}
# the table abbreviates to fit a narrow column; prose spells the model out
PROSE = {"Logistic reg.": "logistic regression", "Random forest": "the random forest",
         "Gradient boost.": "gradient boosting"}
pf["_d"] = pf[KEY["Copilot v1"]] - pf[KEY[best_classic["name"]]]
d_seed = pf.groupby("seed")["_d"].mean()
diff, diff_sd = float(d_seed.mean()), float(d_seed.std(ddof=1))
sa, sb = pro["primary_std_over_folds"], best_classic["primary_std_over_folds"]
clears = abs(diff) > max(sa, sb)

loop = E[("ablation", "cnn")]
retr = E[("ablation", "proposed")]
c = pro["cost"]
defer_pro, defer_abl = hl.loc["proposed", "defer_pct"], hl.loc["ablation", "defer_pct"]
acc_pro, acc_abl = (hl.loc["proposed", "acc_when_generate"],
                    hl.loc["ablation", "acc_when_generate"])

# The article writes numbers below ten as words, and this paragraph is spliced
# into it, so the generator follows the same rule. Ten and above stay in digits,
# which is why the fold count on the next line is still %d.
_PALABRAS = ["zero", "one", "two", "three", "four", "five",
             "six", "seven", "eight", "nine"]
EN_PALABRAS = lambda n: _PALABRAS[n] if 0 <= n < 10 else str(n)

S = [
 ("what is compared, and on what partition",
  "Eight systems are compared on the Tennessee Eastman Process under one protocol: a "
  "trivial floor, three classical models, two networks, and the copilot with its "
  "ablation, all scored on validation folds of a partition frozen by simulation run "
  "with the test set sealed, over %d folds from %s seeds."
  % (d["_meta"]["folds_per_seed"] * len(d["_meta"]["seeds"]), EN_PALABRAS(len(d["_meta"]["seeds"])))),
 ("the proposed method, with its dispersion",
  "The proposed copilot reaches $%.3f \\pm %.3f$ macro-averaged $F_1$ and "
  "$%.3f \\pm %.3f$ Recall@3."
  % (pro["primary_mean"], pro["primary_std_over_folds"],
     pro["secondary_mean"], pro["secondary_std_over_folds"])),
 ("the difference against the best classic, and whether it clears the dispersion",
  "Against the best classical model, %s at $%.3f \\pm %.3f$, the paired difference is "
  "$%+.3f \\pm %.3f$ over the seeds, which is %s than either dispersion and keeps its "
  "sign in all %d folds."
  % (PROSE[best_classic["name"]], best_classic["primary_mean"],
     best_classic["primary_std_over_folds"], diff, diff_sd,
     "larger" if clears else "smaller", int((pf["_d"] > 0).sum() if diff > 0 else (pf["_d"] < 0).sum()))),
 ("what the agent adds, read off the ablation",
  "The ablation separates the two things the agent does: the loop is worth "
  "$%+.3f \\pm %.3f$ with $d = %.1f$ over the same network scored once, while retrieval "
  "costs $%.3f$ on the primary metric, so the proposed method does not beat its own "
  "ablation there."
  % (loop.paired_diff, loop.std_over_seeds, abs(loop.cohens_d), abs(retr.paired_diff))),
 # The latency is wall-clock and moves with the processor: the same copilot
 # measured 0.197, 0.123 and 0.254 ms on three machines on 2026-09-19. Three
 # decimals in prose would be a number a reproducer cannot match, which is the
 # reason Section IV stopped quoting training seconds two days earlier. The
 # exact value for this run stays in Table II and in cost_table.csv; the
 # sentence claims only what survives the move, and the point it carries is
 # that the loop costs nothing perceivable.
 ("the cost",
  "It stores %s numbers, trains nothing because it loads the network saved for each "
  "fold, answers in under a millisecond per episode, and calls no language model, so "
  "its token count is zero."
  % ("{:,}".format(c["parameters"]),)),
 ("the main limitation",
  "The main limitation is coverage rather than accuracy: requiring the classifier and "
  "the retrieval to agree makes the copilot hand %.0f\\%% of episodes to the operator "
  "against %.0f\\%% for the ablation, while accuracy on the episodes it does answer "
  "goes from %.1f\\%% to %.1f\\%%."
  % (defer_pro, defer_abl, acc_abl, acc_pro)),
]

md = ["# Results, in six sentences", "",
      "Generated by `resultados.py` from `results/tabla2.json` and the effect-size and",
      "human-load records. Every number is substituted, none is typed.", "",
      "| # | what the sentence has to carry |", "|---|---|"]
md += ["| %d | %s |" % (i, lab) for i, (lab, _) in enumerate(S, 1)]
md += ["", "---", "", " ".join(t for _, t in S).replace("\\\\", "\\"), "", "---", "",
       "## Sentence by sentence", ""]
for i, (lab, t) in enumerate(S, 1):
    md += ["**%d. %s**" % (i, lab), "", t.replace("\\\\", "\\"), ""]

OUTMD = os.path.join(BASE, "paper", "resultados.md")
if not CHECK:
    io.open(OUTMD, "w", encoding="utf-8", newline="\n").write("\n".join(md) + "\n")
    print("wrote paper/resultados.md  (%d sentences)" % len(S))

# el mismo parrafo, en LaTeX y dentro del manuscrito. Las frases ya vienen
# escritas en LaTeX, asi que solo se reparten en lineas para poder leer el .tex
para = " ".join(t for _, t in S)
body = "\n".join(textwrap.wrap(para, 78, break_long_words=False, break_on_hyphens=False))
OUTTEX = os.path.join(BASE, "paper", "resultados.tex")
io.open(OUTTEX, "w", encoding="utf-8", newline="\n").write(body + "\n")

if CHECK:
    FILES_OK.append(compare(OUTTEX, body, "paper/resultados.tex"))

tex = io.open(TEX, encoding="utf-8").read() if HAS_TEX else ""
i, j = (tex.find(PBEGIN), tex.find(PEND)) if HAS_TEX else (-1, -1)
assert (i >= 0 and j > i) or not HAS_TEX, "faltan los marcadores del parrafo en el manuscrito"
had = tex[i + len(PBEGIN):j].strip() if HAS_TEX else body.strip()
if CHECK:
    ok = had == body.strip()
    if HAS_TEX:
        print("el parrafo de Results %s lo que generan los datos"
              % ("COINCIDE con" if ok else "NO coincide con"))
    # no se sale todavia: falta la tabla del README, que es la tercera region
    CHECKS = [same, ok] if HAS_TEX else []
elif not HAS_TEX:
    pass
elif had == body.strip():
    print("el manuscrito ya llevaba este parrafo: no se toco")
else:
    io.open(TEX, "w", encoding="utf-8", newline="\n").write(
        tex[:i + len(PBEGIN)] + "\n" + body + "\n" + tex[j:])
    print("manuscrito actualizado con el parrafo generado")


# ------------------------------------------- the expected-results table of the README
# It carried six stale inference times, the same ones PROTOCOLO.md had. A table
# written by hand drifts, so this one is written from the same file as Table II.
#
# The third column is SIZE, not the inference latency it used to be. The section
# is headed "Expected results (frozen)" and latency is the one value there that is
# not frozen: it is wall-clock, it moved between two runs on the same machine on
# 2026-09-18 (0.100 to 0.105 ms for the ablation), and it moves further on another
# machine. Someone reproducing would compare against a table that says frozen,
# find the last column different, and think something broke. Size is a count of
# the numbers a model stores to decide, so it is reproducible like the metrics.
# The three cost values together stay in Table II, where the header says what
# they are and no one is promised they are frozen.
NAMES = {"Trivial": "Trivial (majority)", "Logistic reg.": "Logistic regression",
         "Random forest": "Random forest", "Gradient boost.": "Gradient boosting",
         "v1a MLP": "Neural net v1a (MLP)", "v1b 1D-CNN": "Neural net v1b (1D-CNN)",
         "No agent (abl.)": "**No agent (ablation)**", "Copilot v1": "Copilot v1 (proposed)"}
rows = ["| Model | F1-macro | Recall@3 | Size (numbers stored) |", "|---|---|---|---|"]
for m in models:
    b = "**" if m["name"] == best_p else ""
    rows.append("| %s | %s%.3f \u00b1 %.3f%s | %s%.3f \u00b1 %.3f%s | %s |"
                % (NAMES[m["name"]], b, m["primary_mean"], m["primary_std_over_folds"], b,
                   b, m["secondary_mean"], m["secondary_std_over_folds"], b,
                   "{:,}".format(m["cost"]["parameters"])))
tabla_readme = "\n".join(rows)

RM = os.path.join(BASE, "README.md")
RB = "<!-- BEGIN esperados (generated by resultados.py; do not edit by hand) -->"
RE_ = "<!-- END esperados -->"
rm = io.open(RM, encoding="utf-8").read()
i, j = rm.find(RB), rm.find(RE_)
assert i >= 0 and j > i, "faltan los marcadores de la tabla esperada en el README"
had = rm[i + len(RB):j].strip()
if CHECK:
    ok3 = had == tabla_readme.strip()
    print("la tabla esperada del README %s lo que generan los datos"
          % ("COINCIDE con" if ok3 else "NO coincide con"))
    raise SystemExit(0 if all(CHECKS + FILES_OK + [ok3]) else 1)
elif had == tabla_readme.strip():
    print("el README ya llevaba estos numeros: no se toco")
else:
    io.open(RM, "w", encoding="utf-8", newline="\n").write(
        rm[:i + len(RB)] + "\n" + tabla_readme + "\n" + rm[j:])
    print("README actualizado con la tabla generada")

print()
print("mejor macro-F1 : %s" % best_p)
print("mejor Recall@3 : %s" % best_s)
print("dispersion     : %s" % d["_meta"]["dispersion_in_table"])
