r"""
Table II and the Results paragraph, written from results/tabla2.json.

Writes the tabular to paper/tabla2.tex and splices that same tabular into the
manuscript between two markers, so the .tex stays one self-contained file to
upload. The caption is not touched: the prose belongs to the authors, the numbers
to the run. The six sentences of paper/resultados.md carry substituted numbers
for the same reason, so the paragraph cannot drift from the table above it.

  python resultados.py           write the table and the paragraph, splice them
  python resultados.py --check   compare only, non-zero if the paper has drifted

The figures come from 09_plot_label_efficiency.py and 13_plot_architecture.py,
not from here.

Reads:  results/tabla2.json, results/effect_sizes.csv, results/per_fold_f1.csv,
        results/human_load.csv, results/rubrica_humana/acuerdo.csv,
        results/agente_comparison.csv, results/errors/twin_runs*.csv and
        results/test/ (written once by 27_test_once.py)
Writes: paper/tabla2.tex, paper/tabla2.csv, paper/resultados.md,
        paper/resultados.tex, paper/rubrica.tex, those three
        regions of the manuscript, the expected-results table of the
        README, and the test-set block of the README and of PROTOCOLO.md
"""
import io
import os
import sys
import json
import re
import textwrap

import numpy as np
import pandas as pd

BASE = os.path.dirname(os.path.abspath(__file__))
if not os.path.isfile(os.path.join(BASE, "requirements.txt")):
    BASE = os.path.dirname(BASE)      # the scripts live in code/, the project one level up
TEX = os.path.join(BASE, "Anteproyecto_G3_Seminario_Tesis_I.tex")
OUT = os.path.join(BASE, "paper", "tabla2.tex")
CSV = os.path.join(BASE, "paper", "tabla2.csv")
PBEGIN = "% BEGIN resultados (generated by resultados.py; do not edit by hand)"
PEND = "% END resultados"
CHECK = "--check" in sys.argv

d = json.load(open(os.path.join(BASE, "results", "tabla2.json"), encoding="utf-8"))
models = d["models"]


def num(mean, std):
    return "$%.3f \\pm %.3f$" % (mean, std)


def cost(c, kind):
    """size / training seconds / inference milliseconds, as the caption defines it.

    An agent row prints 0 because it trains nothing; every other row that rounds to
    zero prints $<$0.01, because it did train and the time is simply small."""
    size = "{:,}".format(c["parameters"])
    t = c["training_seconds"]
    tr = "0" if kind == "agent" else ("$<$0.01" if t < 0.01 else "%.0f" % t)
    inf = "$<$0.001" if c["inference_ms_per_episode"] < 0.001 else "%.3f" % c["inference_ms_per_episode"]
    return "%s / %s / %s" % (size, tr, inf)


# The test column: the same 15 models scored once on the test set by 27. It prints
# the mean only, so the table fits one column; the text of Section V-A gives the
# largest std, which is checked here.
TEST_SUMMARY = os.path.join(BASE, "results", "test", "test_summary.csv")
TKEY = {"Trivial": "trivial", "Logistic reg.": "logistic", "Random forest": "rf",
        "Gradient boost.": "hgb", "v1a MLP": "mlp", "v1b 1D-CNN": "cnn",
        "No agent (abl.)": "ablation", "Copilot v1": "proposed"}
tst = pd.read_csv(TEST_SUMMARY).set_index("row")
TEST_STD_MAX = 0.016                  # Section V-A says "its standard deviation, below 0.016"
assert tst.loc[list(TKEY.values()), "test_F1macro_std"].max() < TEST_STD_MAX, \
    "Section V-A bounds the test standard deviation below %.3f" % TEST_STD_MAX

# the best row on each metric is bold, and it is found here rather than remembered
best_p = max(models, key=lambda m: m["primary_mean"])["name"]
best_s = max(models, key=lambda m: m["secondary_mean"])["name"]
best_t = max(models, key=lambda m: tst.loc[TKEY[m["name"]], "test_F1macro_mean"])["name"]

# la clave de las unidades vive en el encabezado, no en el pie: el pie tiene
# que caber en una linea y esto no cabia
lines = [r"\begin{tabular}{@{}lcccr@{}}", r"\toprule",
         r"& \multicolumn{2}{c}{Macro $F_1$} & & \\", r"\cmidrule(lr){2-3}",
         r"Model & Validation & Test & Recall@3 & \multicolumn{1}{c}{Cost (size / s / ms)} \\",
         r"\midrule"]
# the floor sits with the classics: the rules separate the three families the paper
# discusses, which are the classical models, the networks and the agent arms
BLOCK = {"floor": 0, "classic": 0, "network": 1, "agent": 2}
prev = None
for m in models:
    if prev is not None and BLOCK[m["kind"]] != prev:
        lines.append(r"\midrule")
    prev = BLOCK[m["kind"]]
    p = num(m["primary_mean"], m["primary_std_over_folds"])
    s = num(m["secondary_mean"], m["secondary_std_over_folds"])
    if m["name"] == best_p:
        p = r"$\mathbf{%.3f \pm %.3f}$" % (m["primary_mean"], m["primary_std_over_folds"])
    if m["name"] == best_s:
        s = r"$\mathbf{%.3f \pm %.3f}$" % (m["secondary_mean"], m["secondary_std_over_folds"])
    t = "$%.3f$" % tst.loc[TKEY[m["name"]], "test_F1macro_mean"]
    if m["name"] == best_t:
        t = r"$\mathbf{%.3f}$" % tst.loc[TKEY[m["name"]], "test_F1macro_mean"]
    lines.append("%-15s & %s & %s & %s & %s \\\\" % (m["name"], p, t, s, cost(m["cost"], m["kind"])))
lines += [r"\bottomrule", r"\end{tabular}"]
table = "\n".join(lines)

# The same eight rows as columns, so the table can be read and diffed without
# LaTeX. Full precision: the article rounds to three decimals, this does not.
COLS = ["model", "kind", "f1macro_mean", "f1macro_std_over_folds",
        "test_f1macro_mean", "test_f1macro_std",
        "recall3_mean", "recall3_std_over_folds", "parameters",
        "training_seconds", "inference_ms_per_episode", "tokens"]
csv_rows = [",".join(COLS)]
for m in models:
    c = m["cost"]
    k = TKEY[m["name"]]
    csv_rows.append(",".join(str(v) for v in [
        m["name"], m["kind"], m["primary_mean"], m["primary_std_over_folds"],
        tst.loc[k, "test_F1macro_mean"], tst.loc[k, "test_F1macro_std"],
        m["secondary_mean"], m["secondary_std_over_folds"], c["parameters"],
        c["training_seconds"], c["inference_ms_per_episode"], c["tokens"]]))
tabla_csv = "\n".join(csv_rows)

# The manuscript is not in the repository: it lives in Overleaf and is
# gitignored. A clone therefore has the generated files but not the .tex, so the
# three spliced regions are skipped there instead of crashing, and --check
# reports on what it could actually compare.
HAS_TEX = os.path.isfile(TEX)
if not HAS_TEX:
    print("nota: %s no esta aqui (vive en Overleaf y esta gitignoreado);"
          % os.path.basename(TEX))
    print("      se generan y comparan los archivos versionados, no el manuscrito")

tex = io.open(TEX, encoding="utf-8").read() if HAS_TEX else ""
# lc+r matches the table before and after the test column; Table I ends in c, not r
current = re.search(r"\\begin\{tabular\}\{@\{\}lc+r@\{\}\}.*?\\end\{tabular\}", tex, re.S)
assert current or not HAS_TEX, "no se encontro la tabular de la Tabla II en el manuscrito"
same = current.group(0).strip() == table.strip() if current else True

# paper/tabla2.tex and paper/resultados.tex are committed, so they can be compared
# on a clone even when the manuscript is not here. This is what CI checks.
def compare(path, want, label):
    if not os.path.isfile(path):
        print("%s: no existe todavia" % label)
        return False
    got = io.open(path, encoding="utf-8").read().strip()
    ok = got == want.strip()
    print("%s %s lo que generan los datos" % (label, "COINCIDE con" if ok else "NO coincide con"))
    return ok

FILES_OK = []
if CHECK:
    FILES_OK.append(compare(OUT, table, "paper/tabla2.tex"))
    FILES_OK.append(compare(CSV, tabla_csv, "paper/tabla2.csv"))

if CHECK and not HAS_TEX:
    pass
elif CHECK:
    print("la Tabla II del manuscrito %s lo que generan los datos"
          % ("COINCIDE con" if same else "NO coincide con"))
    if not same:
        for a, b in zip(current.group(0).splitlines(), table.splitlines()):
            if a.strip() != b.strip():
                print("  manuscrito: %s\n  generado  : %s" % (a.strip(), b.strip()))
else:
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    io.open(OUT, "w", encoding="utf-8", newline="\n").write(table + "\n")
    io.open(CSV, "w", encoding="utf-8", newline="\n").write(tabla_csv + "\n")
    print("wrote paper/tabla2.tex and paper/tabla2.csv")
    if not HAS_TEX:
        pass
    elif same:
        print("el manuscrito ya llevaba estos numeros: no se toco")
    else:
        tex = tex[:current.start()] + table + tex[current.end():]
        io.open(TEX, "w", encoding="utf-8", newline="\n").write(tex)
        print("manuscrito actualizado con la tabla generada")
# ---------------------------------------------------------------- the paragraph
M = {m["name"]: m for m in models}
eff = pd.read_csv(os.path.join(BASE, "results", "effect_sizes.csv"))
pf = pd.read_csv(os.path.join(BASE, "results", "per_fold_f1.csv"))
hl = pd.read_csv(os.path.join(BASE, "results", "human_load.csv")).set_index("arm")
E = {(r.better, r.worse): r for r in eff.itertuples()}

pro, abl = M["Copilot v1"], M["No agent (abl.)"]
classics = [M[n] for n in ("Logistic reg.", "Random forest", "Gradient boost.")]
best_classic = max(classics, key=lambda m: m["primary_mean"])

# [3] the difference against the best classic, paired fold by fold and averaged by
# seed, which is how every other comparison in this paper is taken
KEY = {"Copilot v1": "proposed", "Logistic reg.": "logistic",
       "Random forest": "rf", "Gradient boost.": "hgb"}
# the table abbreviates to fit a narrow column; prose spells the model out
PROSE = {"Logistic reg.": "logistic regression", "Random forest": "the random forest",
         "Gradient boost.": "gradient boosting"}
pf["_d"] = pf[KEY["Copilot v1"]] - pf[KEY[best_classic["name"]]]
d_seed = pf.groupby("seed")["_d"].mean()
diff, diff_sd = float(d_seed.mean()), float(d_seed.std(ddof=1))
sa, sb = pro["primary_std_over_folds"], best_classic["primary_std_over_folds"]
clears = abs(diff) > max(sa, sb)

loop = E[("ablation", "cnn")]
retr = E[("ablation", "proposed")]
# [4] Neither gain is printed with the interval it had. "+0.056 +- 0.001" excluded
# the 0.0541 a Ryzen 7600X returns, and an interval that excludes another machine
# was too precise to begin with; the Cohen's d beside it fell from 7.00 to 4.45 on
# that same machine, because d divides by a spread the networks do not reproduce.
# So both gains are stated to the hundredth every processor agrees on, and the
# claim rests on the sign of all fifteen folds, which is what reproduces.
# PROTOCOLO.md records which effect sizes survived and why these two did not.
PISO = lambda x: float(np.floor(abs(x) * 100) / 100)    # "more than", so it rounds down
CERCA = lambda x: round(abs(x), 2)                      # "about", so it rounds to nearest
loop_folds = int((pf["ablation"] - pf["cnn"] > 0).sum())
c = pro["cost"]
# the cost sentence says "under a millisecond" and "trains nothing" in words, so the
# words are checked against the run instead of trusted
assert c["inference_ms_per_episode"] < 1.0 and c["training_seconds"] == 0, c
defer_pro, defer_abl = hl.loc["proposed", "defer_pct"], hl.loc["ablation", "defer_pct"]
acc_pro, acc_abl = (hl.loc["proposed", "acc_when_generate"],
                    hl.loc["ablation", "acc_when_generate"])

# The same comparisons on the test set, from the 15 models 27 scored once, paired
# fold by fold and averaged by seed as on validation. What the sentences say about
# them in words is asserted here.
TDIR = os.path.join(BASE, "results", "test")
tpf = pd.read_csv(os.path.join(TDIR, "test_per_fold.csv"))
tper = lambda r: tpf[tpf["row"] == r].set_index(["seed", "fold"])["F1macro"]
t_cls = tper("proposed") - tper(KEY[best_classic["name"]])
t_loop = tper("ablation") - tper("cnn")
t_retr = tper("proposed") - tper("ablation")
t_cls_s, t_retr_s = t_cls.groupby(level=0).mean(), t_retr.groupby(level=0).mean()
assert (t_cls > 0).all(), "the paragraph says the gap over the best classic keeps its sign in every test fold"
assert loop_folds == len(pf) and (t_loop > 0).all(), "the paragraph says the loop gains in every fold of both sets"
assert 0 < t_retr_s.mean() < max(tst.loc["ablation", "test_F1macro_std"], tst.loc["proposed", "test_F1macro_std"]), \
    "the paragraph says the copilot is ahead of its ablation on test, inside the dispersion"
tdec = pd.read_csv(os.path.join(TDIR, "decisions_test.csv.gz"),
                   usecols=["seed", "fold", "arm", "action", "y", "top1"])


def t_load(arm):
    """Share deferred and accuracy when answering, per fold and then averaged, as 15 does."""
    x = tdec[tdec["arm"] == arm]
    defer = x["action"].eq("defer").groupby([x["seed"], x["fold"]]).mean().mean()
    g = x[x["action"] == "generate"]
    acc = g["y"].eq(g["top1"]).groupby([g["seed"], g["fold"]]).mean().mean()
    return 100 * defer, 100 * acc


t_def_pro, t_acc_pro = t_load("proposed")
t_def_abl, t_acc_abl = t_load("ablation")

# The article writes numbers below ten as words, and this paragraph is spliced
# into it, so the generator follows the same rule. Ten and above stay in digits,
# which is why the fold count on the next line is still %d.
_PALABRAS = ["zero", "one", "two", "three", "four", "five",
             "six", "seven", "eight", "nine"]
EN_PALABRAS = lambda n: _PALABRAS[n] if 0 <= n < 10 else str(n)

S = [
 ("what is compared, and on what partition",
  "Eight systems are compared on the Tennessee Eastman Process under one protocol: a "
  "trivial floor, three classical models, two networks, and the copilot with its "
  "ablation, all scored on validation folds of a partition frozen by simulation run, "
  "over %d folds from %s seeds, and the same %d models once more on the held-out test set."
  % (d["_meta"]["folds_per_seed"] * len(d["_meta"]["seeds"]), EN_PALABRAS(len(d["_meta"]["seeds"])),
     len(tpf[tpf["row"] == "proposed"]))),
 ("the proposed method, with its dispersion",
  "The proposed copilot reaches $%.3f \\pm %.3f$ macro-averaged $F_1$ and "
  "$%.3f \\pm %.3f$ Recall@3 on validation, and $%.3f$ macro-$F_1$ on test."
  % (pro["primary_mean"], pro["primary_std_over_folds"],
     pro["secondary_mean"], pro["secondary_std_over_folds"],
     tst.loc["proposed", "test_F1macro_mean"])),
 ("the difference against the best classic, and whether it clears the dispersion",
  "Against the best classical model, %s at $%.3f \\pm %.3f$, the paired difference is "
  "$%+.3f \\pm %.3f$ over the seeds, which is %s than either dispersion and keeps its "
  "sign in all %d folds, and it is $%+.3f \\pm %.3f$ on test, again in all %d."
  % (PROSE[best_classic["name"]], best_classic["primary_mean"],
     best_classic["primary_std_over_folds"], diff, diff_sd,
     "larger" if clears else "smaller", int((pf["_d"] > 0).sum() if diff > 0 else (pf["_d"] < 0).sum()),
     t_cls_s.mean(), t_cls_s.std(ddof=1), len(t_cls))),
 ("what the agent adds, read off the ablation",
  "The ablation separates the two things the agent does: the loop is worth more than "
  "$%.2f$ macro-$F_1$ over the same network scored once on validation and more than "
  "$%.2f$ on test, with the same sign in all %d folds of both, while retrieval costs "
  "about $%.2f$ on validation, so the proposed method does not beat its own ablation "
  "there, and is ahead of it on test by $%+.3f \\pm %.3f$ over the seeds, inside the "
  "dispersion."
  % (PISO(loop.paired_diff), PISO(t_loop.mean()), loop_folds, CERCA(retr.paired_diff),
     t_retr_s.mean(), t_retr_s.std(ddof=1))),
 # The latency is wall-clock and moves with the processor: the same copilot
 # measured 0.197, 0.123 and 0.254 ms on three machines on 2026-09-19. Three
 # decimals in prose would be a number a reproducer cannot match, which is the
 # reason Section IV stopped quoting training seconds two days earlier. The
 # exact value for this run stays in Table II and in cost_table.csv; the
 # sentence claims only what survives the move, and the point it carries is
 # that the loop costs nothing perceivable.
 ("the cost",
  "It stores %s numbers, trains nothing because it loads the network saved for each "
  "fold, answers in under a millisecond per episode, and calls no language model, so "
  "its token count is zero."
  % ("{:,}".format(c["parameters"]),)),
 ("the main limitation",
  "The main limitation is coverage rather than accuracy: requiring the classifier and "
  "the retrieval to agree makes the copilot hand %.0f\\%% of episodes to the operator "
  "against %.0f\\%% for the ablation, while accuracy on the episodes it does answer "
  "goes from %.1f\\%% to %.1f\\%%; on test it hands over %.0f\\%% against %.0f\\%% and "
  "goes from %.1f\\%% to %.1f\\%%."
  % (defer_pro, defer_abl, acc_abl, acc_pro, t_def_pro, t_def_abl, t_acc_abl, t_acc_pro)),
]

md = ["# Results, in six sentences", "",
      "Generated by `resultados.py` from `results/tabla2.json` and the effect-size and",
      "human-load records. Every number is substituted, none is typed.", "",
      "| # | what the sentence has to carry |", "|---|---|"]
md += ["| %d | %s |" % (i, lab) for i, (lab, _) in enumerate(S, 1)]
md += ["", "---", "", " ".join(t for _, t in S).replace("\\\\", "\\"), "", "---", "",
       "## Sentence by sentence", ""]
for i, (lab, t) in enumerate(S, 1):
    md += ["**%d. %s**" % (i, lab), "", t.replace("\\\\", "\\"), ""]

OUTMD = os.path.join(BASE, "paper", "resultados.md")
if CHECK:
    FILES_OK.append(compare(OUTMD, "\n".join(md), "paper/resultados.md"))
else:
    io.open(OUTMD, "w", encoding="utf-8", newline="\n").write("\n".join(md) + "\n")
    print("wrote paper/resultados.md  (%d sentences)" % len(S))

# el mismo parrafo, en LaTeX y dentro del manuscrito. Las frases ya vienen
# escritas en LaTeX, asi que solo se reparten en lineas para poder leer el .tex
para = " ".join(t for _, t in S)
body = "\n".join(textwrap.wrap(para, 78, break_long_words=False, break_on_hyphens=False))
OUTTEX = os.path.join(BASE, "paper", "resultados.tex")
# --check only compares: writing first and then comparing the file with itself
# would pass whatever the file held
if CHECK:
    FILES_OK.append(compare(OUTTEX, body, "paper/resultados.tex"))
else:
    io.open(OUTTEX, "w", encoding="utf-8", newline="\n").write(body + "\n")

tex = io.open(TEX, encoding="utf-8").read() if HAS_TEX else ""
i, j = (tex.find(PBEGIN), tex.find(PEND)) if HAS_TEX else (-1, -1)
assert (i >= 0 and j > i) or not HAS_TEX, "faltan los marcadores del parrafo en el manuscrito"
had = tex[i + len(PBEGIN):j].strip() if HAS_TEX else body.strip()
if CHECK:
    ok = had == body.strip()
    if HAS_TEX:
        print("el parrafo de Results %s lo que generan los datos"
              % ("COINCIDE con" if ok else "NO coincide con"))
    # no se sale todavia: falta la tabla del README, que es la tercera region
    CHECKS = [same, ok] if HAS_TEX else []
elif not HAS_TEX:
    pass
elif had == body.strip():
    print("el manuscrito ya llevaba este parrafo: no se toco")
else:
    io.open(TEX, "w", encoding="utf-8", newline="\n").write(
        tex[:i + len(PBEGIN)] + "\n" + body + "\n" + tex[j:])
    print("manuscrito actualizado con el parrafo generado")


# -------------------------------------------------- the human rubric, in one sentence
# It reached no agreement beyond chance, and that is the result. The numbers come
# from 24_acuerdo_rubrica.py, which is not part of run_all.py, so the region is
# skipped when acuerdo.csv is not here instead of crashing.
ACU = os.path.join(BASE, "results", "rubrica_humana", "acuerdo.csv")
RBEGIN = "% BEGIN rubrica (generated by resultados.py; do not edit by hand)"
REND = "% END rubrica"
if not os.path.isfile(ACU):
    print("nota: results/rubrica_humana/acuerdo.csv no esta; el parrafo de la rubrica se omite")
else:
    ac = pd.read_csv(ACU).set_index("item")
    cubren = ((ac["ic95_bajo"] <= 0) & (ac["ic95_alto"] >= 0)).all()
    R = [
     "A human rubric of %s binary items, scored on %d sampled episodes by two raters "
     "who did not confer, reached no agreement beyond chance on any item, with Cohen's "
     "$\\kappa$ from $%+.2f$ to $%+.2f$ and %s 95\\%% interval containing zero, so it "
     "measures the rubric and not the explanations."
     % (EN_PALABRAS(len(ac)), int(ac["n"].iloc[0]), ac["kappa"].min(),
        ac["kappa"].max(), "every" if cubren else "not every"),
    ]
    rub = "\n".join(textwrap.wrap(" ".join(R), 78, break_long_words=False,
                                  break_on_hyphens=False))
    OUTRUB = os.path.join(BASE, "paper", "rubrica.tex")
    if CHECK:
        FILES_OK.append(compare(OUTRUB, rub, "paper/rubrica.tex"))
    else:
        io.open(OUTRUB, "w", encoding="utf-8", newline="\n").write(rub + "\n")
    tex = io.open(TEX, encoding="utf-8").read() if HAS_TEX else ""
    i, j = (tex.find(RBEGIN), tex.find(REND)) if HAS_TEX else (-1, -1)
    assert (i >= 0 and j > i) or not HAS_TEX, "faltan los marcadores de la rubrica en el manuscrito"
    had = tex[i + len(RBEGIN):j].strip() if HAS_TEX else rub.strip()
    if CHECK and HAS_TEX:
        okr = had == rub.strip()
        print("el parrafo de la rubrica %s lo que generan los datos"
              % ("COINCIDE con" if okr else "NO coincide con"))
        CHECKS.append(okr)
    elif CHECK or not HAS_TEX:
        pass
    elif had == rub.strip():
        print("el manuscrito ya llevaba el parrafo de la rubrica: no se toco")
    else:
        io.open(TEX, "w", encoding="utf-8", newline="\n").write(
            tex[:i + len(RBEGIN)] + "\n" + rub + "\n" + tex[j:])
        print("manuscrito actualizado con el parrafo de la rubrica")


# ------------------------------------------- the expected-results table of the README
# It carried six stale inference times, the same ones PROTOCOLO.md had. A table
# written by hand drifts, so this one is written from the same file as Table II.
#
# The third column is SIZE, not the inference latency it used to be. The section
# is headed "Expected results (frozen)" and latency is the one value there that is
# not frozen: it is wall-clock, it moved between two runs on the same machine on
# 2026-09-18 (0.100 to 0.105 ms for the ablation), and it moves further on another
# machine. Someone reproducing would compare against a table that says frozen,
# find the last column different, and think something broke. Size is a count of
# the numbers a model stores to decide, so it is reproducible like the metrics.
# The three cost values together stay in Table II, where the header says what
# they are and no one is promised they are frozen.
NAMES = {"Trivial": "Trivial (majority)", "Logistic reg.": "Logistic regression",
         "Random forest": "Random forest", "Gradient boost.": "Gradient boosting",
         "v1a MLP": "Neural net v1a (MLP)", "v1b 1D-CNN": "Neural net v1b (1D-CNN)",
         "No agent (abl.)": "**No agent (ablation)**", "Copilot v1": "Copilot v1 (proposed)"}
rows = ["| Model | F1-macro | Recall@3 | Size (numbers stored) |", "|---|---|---|---|"]
for m in models:
    b = "**" if m["name"] == best_p else ""
    rows.append("| %s | %s%.3f \u00b1 %.3f%s | %s%.3f \u00b1 %.3f%s | %s |"
                % (NAMES[m["name"]], b, m["primary_mean"], m["primary_std_over_folds"], b,
                   b, m["secondary_mean"], m["secondary_std_over_folds"], b,
                   "{:,}".format(m["cost"]["parameters"])))
tabla_readme = "\n".join(rows)


# --------------------------------------------- the test set, opened once by 27
# One block, spliced into the README and into PROTOCOLO.md. The prose around it
# in both files carries no number, so every claim that prose makes in words is
# asserted below against results/test/ and the validation files.
TD = os.path.join(BASE, "results", "test")
TB = "<!-- BEGIN prueba (generated by resultados.py from results/test/; do not edit by hand) -->"
TE = "<!-- END prueba -->"
TEST_OK = []


def region(path, content, label):
    txt = io.open(path, encoding="utf-8").read()
    a, b = txt.find(TB), txt.find(TE)
    assert a >= 0 and b > a, "faltan los marcadores del bloque del test en %s" % label
    old = txt[a + len(TB):b].strip()
    if CHECK:
        ok = old == content.strip()
        print("el bloque del test en %s %s lo que generan los datos"
              % (label, "COINCIDE con" if ok else "NO coincide con"))
        return ok
    if old != content.strip():
        io.open(path, "w", encoding="utf-8", newline="\n").write(
            txt[:a + len(TB)] + "\n" + content + "\n" + txt[b:])
        print("%s actualizado con el bloque del test" % label)
    return True


if not os.path.isfile(os.path.join(TD, "test_summary.csv")):
    print("nota: results/test/ no esta; el bloque del test se omite")
else:
    ts = pd.read_csv(os.path.join(TD, "test_summary.csv")).set_index("row")
    tp = pd.read_csv(os.path.join(TD, "test_per_fold.csv"))
    tw = pd.read_csv(os.path.join(TD, "twins.csv")).set_index("class")
    ag = pd.read_csv(os.path.join(BASE, "results", "agente_comparison.csv")).set_index("arm")
    vt = pd.read_csv(os.path.join(BASE, "results", "errors", "twin_runs.csv")).set_index("fault")
    vts = pd.read_csv(os.path.join(BASE, "results", "errors", "twin_runs_summary.csv"))
    TROWS = [("trivial", "Trivial"), ("logistic", "Logistic reg."), ("rf", "Random forest"),
             ("hgb", "Gradient boost."), ("mlp", "v1a MLP"), ("cnn", "v1b 1D-CNN"),
             ("ablation", "No agent (abl.)"), ("proposed", "Copilot v1")]

    def per(row, met):
        return tp[tp["row"] == row].set_index(["seed", "fold"])[met]

    def tmean(row, met):
        return float(per(row, met).mean())

    pm = lambda m, s: "%.3f ± %.3f" % (m, s)
    pct = lambda x: "%.1f%%" % (100 * x)
    d_val = pf["proposed"] - pf["ablation"]
    d_tst = per("proposed", "F1macro") - per("ablation", "F1macro")
    gain_val = {a: pf["rootkb_" + a] - pf["rootchrono_" + a] for a in ("lookup", "proposed")}
    gain_tst = {a: per(a, "RootAlarmKB") - per(a, "RootAlarmChrono") for a in ("lookup", "proposed")}

    # what the prose says in words, checked against the numbers
    learned = [r for r, _ in TROWS if r != "trivial"]
    assert (ts.loc[learned, "test_F1macro_mean"] < ts.loc[learned, "val_F1macro_mean"]).all(), \
        "the prose says every learned row is lower on the test set"
    assert (ts.loc[["logistic", "rf", "hgb"], "test_Recall@3_mean"]
            > ts.loc[["logistic", "rf", "hgb"], "val_Recall@3_mean"]).all(), \
        "the prose says Recall@3 rises for the three classical models"
    assert ((ts.loc[learned, "test_Recall@3_mean"] - ts.loc[learned, "val_Recall@3_mean"])
            > (ts.loc[learned, "test_F1macro_mean"] - ts.loc[learned, "val_F1macro_mean"])).all(),         "the prose says Recall@3 drops less than macro-F1 on every row"
    assert (d_val < 0).all(), "the prose says the ablation is ahead in every validation fold"
    assert 0 < d_tst.mean() < max(ts.loc["ablation", "test_F1macro_std"],
                                  ts.loc["proposed", "test_F1macro_std"]), \
        "the prose says the sign reverses on the test set, inside the dispersion"
    assert (d_tst > 0).sum() > len(d_tst) / 2, "the prose says the copilot is ahead in most test folds"
    assert all((g > 0).all() for g in list(gain_val.values()) + list(gain_tst.values())), \
        "the prose says the documents beat chronology in every fold, both arms, both sets"
    assert tmean("proposed", "AccAgree") > tmean("proposed", "AccDisagree"), \
        "the prose says agreement still separates right from wrong on the test set"
    assert (tw["pre_onset_equal_any_dev_run"] == 0).all(), \
        "the prose says no test run repeats a development run before onset"
    assert set(tw.index[tw["twin_scored_window"] > 0]) - {0} == set(vt.index), \
        "the prose says the twins fall on the same faults in both pools"

    B = ["**Table II on the test set, next to validation.** Mean ± std over the "
         "15 validation models; on test each of them scores all 10,500 test runs.", "",
         "| Model | F1-macro, validation | F1-macro, test | Recall@3, validation | Recall@3, test |",
         "|---|---|---|---|---|"]
    for r, n in TROWS:
        s = ts.loc[r]
        B.append("| %s | %s | %s | %s | %s |" % (
            NAMES[n].replace("**", ""), pm(s["val_F1macro_mean"], s["val_F1macro_std"]),
            pm(s["test_F1macro_mean"], s["test_F1macro_std"]),
            pm(s["val_Recall@3_mean"], s["val_Recall@3_std"]),
            pm(s["test_Recall@3_mean"], s["test_Recall@3_std"])))

    def ahead(who, x):
        return "%s ahead in %d of %d folds" % (who, int((x > 0).sum()), len(x))

    B += ["", "**What the agent does, on validation and on test.** Paired differences "
          "are taken fold by fold, mean ± std over the 15 folds.", "",
          "| Measure | Validation | Test |", "|---|---|---|",
          "| Copilot minus ablation, macro-F1 | %+.3f ± %.3f, %s | %+.3f ± %.3f, %s |"
          % (d_val.mean(), d_val.std(ddof=0), ahead("copilot", d_val),
             d_tst.mean(), d_tst.std(ddof=0), ahead("copilot", d_tst))]
    for a, lab in (("lookup", "label-anchored arm: by time / by the predicted class's documents"),
                   ("proposed", "proposed arm: by time / by the retrieved documents")):
        B.append("| Root alarm, %s | %.3f / %.3f, documents %s | %.3f / %.3f, documents %s |"
                 % (lab, ag.loc[a, "RootAlarmChrono_mean"], ag.loc[a, "RootAlarmKB_mean"],
                    ahead("", gain_val[a]).strip(), tmean(a, "RootAlarmChrono"),
                    tmean(a, "RootAlarmKB"), ahead("", gain_tst[a]).strip()))
    B += ["| Episodes where classifier and retrieval agree | %s | %s |"
          % (pct(ag.loc["proposed", "AgreeShare_mean"]), pct(tmean("proposed", "AgreeShare"))),
          "| Right when they agree / when they disagree | %s / %s | %s / %s |"
          % (pct(ag.loc["proposed", "AccAgree_mean"]), pct(ag.loc["proposed", "AccDisagree_mean"]),
             pct(tmean("proposed", "AccAgree")), pct(tmean("proposed", "AccDisagree"))),
          "| Episodes deferred to the operator, copilot / ablation | %s / %s | %s / %s |"
          % (pct(ag.loc["proposed", "act_defer_mean"]), pct(ag.loc["ablation", "act_defer_mean"]),
             pct(tmean("proposed", "act_defer")), pct(tmean("ablation", "act_defer"))),
          "| Fewer alarms shown than raised, copilot | %s | %s |"
          % (pct(ag.loc["proposed", "AlarmReduction_mean"]), pct(tmean("proposed", "AlarmReduction")))]

    tot_dev = int(vts.loc[(vts["scope"] == "scored [21,41)") & (vts["measure"] == "runs in twin groups"),
                          "value"].iloc[0])
    B += ["", "**Twin runs**, byte-identical to another run over the scored window, "
          "[21, 41) in the development pool and [161, 181) in the test pool.", "",
          "| Class | Development pool | Test pool |", "|---|---|---|",
          "| Normal operation | %d | %d |" % (tot_dev - int(vt["twin_scored_window"].sum()),
                                             int(tw.loc[0, "twin_scored_window"]))]
    for f in vt.index:
        B.append("| IDV(%d) | %d | %d |" % (f, vt.loc[f, "twin_scored_window"],
                                            tw.loc[f, "twin_scored_window"]))
    B += ["| All runs in twin groups | {:,} | {:,} |".format(tot_dev, int(tw["twin_scored_window"].sum())),
          "", "Test runs that repeat a development run over samples 1 to 20, before either "
          "onset: %d of {:,}.".format(int(tw["runs"].sum())) % int(tw["pre_onset_equal_any_dev_run"].sum())]
    bloque = "\n".join(B)
    TEST_OK.append(region(os.path.join(BASE, "README.md"), bloque, "el README"))
    TEST_OK.append(region(os.path.join(BASE, "PROTOCOLO.md"), bloque, "PROTOCOLO.md"))

RM = os.path.join(BASE, "README.md")
RB = "<!-- BEGIN esperados (generated by resultados.py; do not edit by hand) -->"
RE_ = "<!-- END esperados -->"
rm = io.open(RM, encoding="utf-8").read()
i, j = rm.find(RB), rm.find(RE_)
assert i >= 0 and j > i, "faltan los marcadores de la tabla esperada en el README"
had = rm[i + len(RB):j].strip()
if CHECK:
    ok3 = had == tabla_readme.strip()
    print("la tabla esperada del README %s lo que generan los datos"
          % ("COINCIDE con" if ok3 else "NO coincide con"))
    raise SystemExit(0 if all(CHECKS + FILES_OK + [ok3] + TEST_OK) else 1)
elif had == tabla_readme.strip():
    print("el README ya llevaba estos numeros: no se toco")
else:
    io.open(RM, "w", encoding="utf-8", newline="\n").write(
        rm[:i + len(RB)] + "\n" + tabla_readme + "\n" + rm[j:])
    print("README actualizado con la tabla generada")

print()
print("mejor macro-F1 : %s" % best_p)
print("mejor Recall@3 : %s" % best_s)
print("dispersion     : %s" % d["_meta"]["dispersion_in_table"])
