"""
The seven sentences of Section IV, copied from the manuscript into PROTOCOLO.md.

The direction matters and is the whole point: the .tex is the source, because it
is the wording that gets reviewed and submitted, and PROTOCOLO receives. Copying
the other way is what let the two drift apart before this script existed.

Aborts if the section does not hold exactly seven sentences.

  python code/siete.py           regenerate the copy in PROTOCOLO.md
  python code/siete.py --check   compare only, non-zero if they differ

The manuscript is gitignored and lives in Overleaf, so a fresh clone does not
have it. That is not an error: the script says so and stops, as resultados.py
does, because there is nothing to check without the source.
"""
import io
import os
import re
import sys

BASE = os.path.dirname(os.path.abspath(__file__))
if not os.path.isfile(os.path.join(BASE, "requirements.txt")):
    BASE = os.path.dirname(BASE)      # the scripts live in code/, the project one level up
TEX = os.path.join(BASE, "Anteproyecto_G3_Seminario_Tesis_I.tex")
PROT = os.path.join(BASE, "PROTOCOLO.md")
BEGIN = "<!-- BEGIN siete (generated by siete.py from the .tex; do not edit by hand) -->"
END = "<!-- END siete -->"
CHECK = "--check" in sys.argv

# "et al." ends in a period and is not the end of a sentence. Without this the
# first sentence splits in two and the section looks like it has eight.
ABREV = ("et al.", "Fig.", "Eq.", "cf.", "e.g.", "i.e.", "vs.", "approx.")
MARCA = "\x00"


def seccion_cuatro(tex):
    """The body of Section IV, with the LaTeX taken out and nothing else changed."""
    L = tex.splitlines()
    # it has been a section, then subsection III-D, and a section again (IV)
    i = next(k for k, l in enumerate(L)
             if re.match(r"\\(sub)?section\{Experimental Configuration\}", l))
    j = next(k for k, l in enumerate(L[i + 1:], i + 1) if re.match(r"\\(sub)?section\{", l))
    t = " ".join(l for l in L[i + 1:j] if not l.strip().startswith("%"))

    t = re.sub(r"\\cite\{[^}]*\}", "", t)          # the protocol copy carries no citations
    t = re.sub(r"\\url\{([^}]*)\}", r"\1", t)
    # a \ref resolves to a number in the PDF and to nothing here, which once left
    # the copy saying "reported per row in Table." Known labels are spelled out;
    # an unknown one is left visible rather than dropped, so it gets noticed.
    for etiqueta, texto in (("tab:results", "II"), ("tab:comparison", "I"),
                            ("fig:architecture", "1"), ("fig:labeleff", "2")):
        t = t.replace("\\ref{%s}" % etiqueta, texto)
    t = re.sub(r"\\ref\{([^}]*)\}", r"[ref:\1]", t)
    t = t.replace("~", " ").replace("\\%", "%").replace("\\&", "&")
    t = re.sub(r"\$([^$]*)\$", r"\1", t)           # math becomes its own text
    t = t.replace("\\{", "{").replace("\\}", "}").replace("_", "_")
    t = re.sub(r"\\[a-zA-Z]+", "", t)              # anything else that is a command
    t = " ".join(t.split())
    # a removed \cite leaves a hole before the punctuation that followed it:
    # "Rieth et al. \cite{rieth2017}, comprising" became "Rieth et al. , comprising"
    t = re.sub(r"\s+([,;:.)])", r"\1", t)
    t = re.sub(r"\(\s+", "(", t)
    return t


def frases(t):
    p = t
    for a in ABREV:
        p = p.replace(a, a.replace(".", MARCA))
    fs = [f.strip().replace(MARCA, ".")
          for f in re.split(r"(?<=\.)\s+(?=[A-Z])", p) if f.strip()]
    return fs


def main():
    if not os.path.isfile(TEX):
        print("nota: %s no esta aqui (vive en Overleaf y esta gitignoreado)."
              % os.path.basename(TEX))
        print("      Este script genera la copia DESDE el manuscrito, asi que sin el")
        print("      no hay nada que generar ni que comparar.")
        return 0

    fs = frases(seccion_cuatro(io.open(TEX, encoding="utf-8").read()))
    if len(fs) != 7:
        print("ABORT - la Seccion IV tiene %d frases y el protocolo declara siete." % len(fs))
        for k, f in enumerate(fs, 1):
            print("   (%d) %s" % (k, f[:76]))
        return 1

    copia = "*Experimental configuration.* " + " ".join(
        "(%d) %s" % (k, f) for k, f in enumerate(fs, 1))
    copia = "\n".join(__import__("textwrap").wrap(copia, 78, break_long_words=False,
                                                  break_on_hyphens=False))

    prot = io.open(PROT, encoding="utf-8").read()
    i, j = prot.find(BEGIN), prot.find(END)
    if i < 0 or j < i:
        print("ABORT - faltan los marcadores de las siete frases en PROTOCOLO.md")
        return 1
    tenia = prot[i + len(BEGIN):j].strip()

    if CHECK:
        ok = tenia == copia.strip()
        print("las siete frases de PROTOCOLO %s la Seccion IV del manuscrito"
              % ("COINCIDEN con" if ok else "NO coinciden con"))
        if not ok:
            for a, b in zip(tenia.splitlines(), copia.splitlines()):
                if a != b:
                    print("   protocolo: %s" % a[:72])
                    print("   .tex     : %s" % b[:72])
                    break
        return 0 if ok else 1

    if tenia == copia.strip():
        print("PROTOCOLO ya llevaba estas siete frases: no se toco")
    else:
        io.open(PROT, "w", encoding="utf-8", newline="\n").write(
            prot[:i + len(BEGIN)] + "\n" + copia + "\n" + prot[j:])
        print("PROTOCOLO actualizado con las siete frases del manuscrito")
    print("   %d frases, %d palabras"
          % (len(fs), len(re.findall(r"[A-Za-z][A-Za-z'-]*", copia))))
    return 0


if __name__ == "__main__":
    sys.exit(main())
